// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product_stock/v1/product_stock.proto

package productstockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductStocksRequest) Reset() {
	*x = ListProductStocksRequest{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductStocksRequest) ProtoMessage() {}

func (x *ListProductStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductStocksRequest.ProtoReflect.Descriptor instead.
func (*ListProductStocksRequest) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{0}
}

type CreateProductStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Brand          string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	AvailableStock int32                  `protobuf:"varint,3,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductStockRequest) Reset() {
	*x = CreateProductStockRequest{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductStockRequest) ProtoMessage() {}

func (x *CreateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductStockRequest.ProtoReflect.Descriptor instead.
func (*CreateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductStockRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductStockRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateProductStockRequest) GetAvailableStock() int32 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

type GetProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductStockRequest) Reset() {
	*x = GetProductStockRequest{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductStockRequest) ProtoMessage() {}

func (x *GetProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductStockRequest.ProtoReflect.Descriptor instead.
func (*GetProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductStockRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductStockRequest) Reset() {
	*x = DeleteProductStockRequest{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductStockRequest) ProtoMessage() {}

func (x *DeleteProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductStockRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteProductStockRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveStockRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListProductStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductStock        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductStocksResponse) Reset() {
	*x = ListProductStocksResponse{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductStocksResponse) ProtoMessage() {}

func (x *ListProductStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductStocksResponse.ProtoReflect.Descriptor instead.
func (*ListProductStocksResponse) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductStocksResponse) GetProducts() []*ProductStock {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductStock          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductStockResponse) Reset() {
	*x = GetProductStockResponse{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductStockResponse) ProtoMessage() {}

func (x *GetProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductStockResponse.ProtoReflect.Descriptor instead.
func (*GetProductStockResponse) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductStockResponse) GetProduct() *ProductStock {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductStockResponse) Reset() {
	*x = CreateProductStockResponse{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductStockResponse) ProtoMessage() {}

func (x *CreateProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductStockResponse.ProtoReflect.Descriptor instead.
func (*CreateProductStockResponse) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductStockResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductStock struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku              string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Brand            string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	AvailableStock   int32                  `protobuf:"varint,5,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	ReservedQuantity int32                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductStock) Reset() {
	*x = ProductStock{}
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStock) ProtoMessage() {}

func (x *ProductStock) ProtoReflect() protoreflect.Message {
	mi := &file_product_stock_v1_product_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStock.ProtoReflect.Descriptor instead.
func (*ProductStock) Descriptor() ([]byte, []int) {
	return file_product_stock_v1_product_stock_proto_rawDescGZIP(), []int{8}
}

func (x *ProductStock) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductStock) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductStock) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductStock) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProductStock) GetAvailableStock() int32 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *ProductStock) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

var File_product_stock_v1_product_stock_proto protoreflect.FileDescriptor

const file_product_stock_v1_product_stock_proto_rawDesc = "" +
	"\n" +
	"$product_stock/v1/product_stock.proto\x12\x10product_stock.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n" +
	"\x18ListProductStocksRequest\"p\n" +
	"\x19CreateProductStockRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12'\n" +
	"\x0favailable_stock\x18\x03 \x01(\x05R\x0eavailableStock\"(\n" +
	"\x16GetProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"+\n" +
	"\x19DeleteProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"A\n" +
	"\x13ReserveStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"W\n" +
	"\x19ListProductStocksResponse\x12:\n" +
	"\bproducts\x18\x01 \x03(\v2\x1e.product_stock.v1.ProductStockR\bproducts\"S\n" +
	"\x17GetProductStockResponse\x128\n" +
	"\aproduct\x18\x01 \x01(\v2\x1e.product_stock.v1.ProductStockR\aproduct\",\n" +
	"\x1aCreateProductStockResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xb2\x01\n" +
	"\fProductStock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12'\n" +
	"\x0favailable_stock\x18\x05 \x01(\x05R\x0eavailableStock\x12+\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x05R\x10reservedQuantity2\x86\x04\n" +
	"\x13ProductStockService\x12l\n" +
	"\x11ListProductStocks\x12*.product_stock.v1.ListProductStocksRequest\x1a+.product_stock.v1.ListProductStocksResponse\x12f\n" +
	"\x0fGetProductStock\x12(.product_stock.v1.GetProductStockRequest\x1a).product_stock.v1.GetProductStockResponse\x12o\n" +
	"\x12CreateProductStock\x12+.product_stock.v1.CreateProductStockRequest\x1a,.product_stock.v1.CreateProductStockResponse\x12Y\n" +
	"\x12DeleteProductStock\x12+.product_stock.v1.DeleteProductStockRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fReserveStock\x12%.product_stock.v1.ReserveStockRequest\x1a\x16.google.protobuf.EmptyBYZWgithub.com/InakiGT/order-processor-system/backend/proto/product_stock/v1;productstockpbb\x06proto3"

var (
	file_product_stock_v1_product_stock_proto_rawDescOnce sync.Once
	file_product_stock_v1_product_stock_proto_rawDescData []byte
)

func file_product_stock_v1_product_stock_proto_rawDescGZIP() []byte {
	file_product_stock_v1_product_stock_proto_rawDescOnce.Do(func() {
		file_product_stock_v1_product_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_stock_v1_product_stock_proto_rawDesc), len(file_product_stock_v1_product_stock_proto_rawDesc)))
	})
	return file_product_stock_v1_product_stock_proto_rawDescData
}

var file_product_stock_v1_product_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_stock_v1_product_stock_proto_goTypes = []any{
	(*ListProductStocksRequest)(nil),   // 0: product_stock.v1.ListProductStocksRequest
	(*CreateProductStockRequest)(nil),  // 1: product_stock.v1.CreateProductStockRequest
	(*GetProductStockRequest)(nil),     // 2: product_stock.v1.GetProductStockRequest
	(*DeleteProductStockRequest)(nil),  // 3: product_stock.v1.DeleteProductStockRequest
	(*ReserveStockRequest)(nil),        // 4: product_stock.v1.ReserveStockRequest
	(*ListProductStocksResponse)(nil),  // 5: product_stock.v1.ListProductStocksResponse
	(*GetProductStockResponse)(nil),    // 6: product_stock.v1.GetProductStockResponse
	(*CreateProductStockResponse)(nil), // 7: product_stock.v1.CreateProductStockResponse
	(*ProductStock)(nil),               // 8: product_stock.v1.ProductStock
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_product_stock_v1_product_stock_proto_depIdxs = []int32{
	8, // 0: product_stock.v1.ListProductStocksResponse.products:type_name -> product_stock.v1.ProductStock
	8, // 1: product_stock.v1.GetProductStockResponse.product:type_name -> product_stock.v1.ProductStock
	0, // 2: product_stock.v1.ProductStockService.ListProductStocks:input_type -> product_stock.v1.ListProductStocksRequest
	2, // 3: product_stock.v1.ProductStockService.GetProductStock:input_type -> product_stock.v1.GetProductStockRequest
	1, // 4: product_stock.v1.ProductStockService.CreateProductStock:input_type -> product_stock.v1.CreateProductStockRequest
	3, // 5: product_stock.v1.ProductStockService.DeleteProductStock:input_type -> product_stock.v1.DeleteProductStockRequest
	4, // 6: product_stock.v1.ProductStockService.ReserveStock:input_type -> product_stock.v1.ReserveStockRequest
	5, // 7: product_stock.v1.ProductStockService.ListProductStocks:output_type -> product_stock.v1.ListProductStocksResponse
	6, // 8: product_stock.v1.ProductStockService.GetProductStock:output_type -> product_stock.v1.GetProductStockResponse
	7, // 9: product_stock.v1.ProductStockService.CreateProductStock:output_type -> product_stock.v1.CreateProductStockResponse
	9, // 10: product_stock.v1.ProductStockService.DeleteProductStock:output_type -> google.protobuf.Empty
	9, // 11: product_stock.v1.ProductStockService.ReserveStock:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_stock_v1_product_stock_proto_init() }
func file_product_stock_v1_product_stock_proto_init() {
	if File_product_stock_v1_product_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_stock_v1_product_stock_proto_rawDesc), len(file_product_stock_v1_product_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_stock_v1_product_stock_proto_goTypes,
		DependencyIndexes: file_product_stock_v1_product_stock_proto_depIdxs,
		MessageInfos:      file_product_stock_v1_product_stock_proto_msgTypes,
	}.Build()
	File_product_stock_v1_product_stock_proto = out.File
	file_product_stock_v1_product_stock_proto_goTypes = nil
	file_product_stock_v1_product_stock_proto_depIdxs = nil
}
