// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: product_stock/v1/product_stock.proto

package productstockpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductStockService_ListProductStocks_FullMethodName  = "/product_stock.v1.ProductStockService/ListProductStocks"
	ProductStockService_GetProductStock_FullMethodName    = "/product_stock.v1.ProductStockService/GetProductStock"
	ProductStockService_CreateProductStock_FullMethodName = "/product_stock.v1.ProductStockService/CreateProductStock"
	ProductStockService_DeleteProductStock_FullMethodName = "/product_stock.v1.ProductStockService/DeleteProductStock"
	ProductStockService_ReserveStock_FullMethodName       = "/product_stock.v1.ProductStockService/ReserveStock"
)

// ProductStockServiceClient is the client API for ProductStockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductStockServiceClient interface {
	ListProductStocks(ctx context.Context, in *ListProductStocksRequest, opts ...grpc.CallOption) (*ListProductStocksResponse, error)
	GetProductStock(ctx context.Context, in *GetProductStockRequest, opts ...grpc.CallOption) (*GetProductStockResponse, error)
	CreateProductStock(ctx context.Context, in *CreateProductStockRequest, opts ...grpc.CallOption) (*CreateProductStockResponse, error)
	DeleteProductStock(ctx context.Context, in *DeleteProductStockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type productStockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductStockServiceClient(cc grpc.ClientConnInterface) ProductStockServiceClient {
	return &productStockServiceClient{cc}
}

func (c *productStockServiceClient) ListProductStocks(ctx context.Context, in *ListProductStocksRequest, opts ...grpc.CallOption) (*ListProductStocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductStocksResponse)
	err := c.cc.Invoke(ctx, ProductStockService_ListProductStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStockServiceClient) GetProductStock(ctx context.Context, in *GetProductStockRequest, opts ...grpc.CallOption) (*GetProductStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductStockResponse)
	err := c.cc.Invoke(ctx, ProductStockService_GetProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStockServiceClient) CreateProductStock(ctx context.Context, in *CreateProductStockRequest, opts ...grpc.CallOption) (*CreateProductStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductStockResponse)
	err := c.cc.Invoke(ctx, ProductStockService_CreateProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStockServiceClient) DeleteProductStock(ctx context.Context, in *DeleteProductStockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductStockService_DeleteProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productStockServiceClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductStockService_ReserveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductStockServiceServer is the server API for ProductStockService service.
// All implementations must embed UnimplementedProductStockServiceServer
// for forward compatibility.
type ProductStockServiceServer interface {
	ListProductStocks(context.Context, *ListProductStocksRequest) (*ListProductStocksResponse, error)
	GetProductStock(context.Context, *GetProductStockRequest) (*GetProductStockResponse, error)
	CreateProductStock(context.Context, *CreateProductStockRequest) (*CreateProductStockResponse, error)
	DeleteProductStock(context.Context, *DeleteProductStockRequest) (*emptypb.Empty, error)
	ReserveStock(context.Context, *ReserveStockRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProductStockServiceServer()
}

// UnimplementedProductStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductStockServiceServer struct{}

func (UnimplementedProductStockServiceServer) ListProductStocks(context.Context, *ListProductStocksRequest) (*ListProductStocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductStocks not implemented")
}
func (UnimplementedProductStockServiceServer) GetProductStock(context.Context, *GetProductStockRequest) (*GetProductStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductStock not implemented")
}
func (UnimplementedProductStockServiceServer) CreateProductStock(context.Context, *CreateProductStockRequest) (*CreateProductStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductStock not implemented")
}
func (UnimplementedProductStockServiceServer) DeleteProductStock(context.Context, *DeleteProductStockRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductStock not implemented")
}
func (UnimplementedProductStockServiceServer) ReserveStock(context.Context, *ReserveStockRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedProductStockServiceServer) mustEmbedUnimplementedProductStockServiceServer() {}
func (UnimplementedProductStockServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductStockServiceServer will
// result in compilation errors.
type UnsafeProductStockServiceServer interface {
	mustEmbedUnimplementedProductStockServiceServer()
}

func RegisterProductStockServiceServer(s grpc.ServiceRegistrar, srv ProductStockServiceServer) {
	// If the following call panics, it indicates UnimplementedProductStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductStockService_ServiceDesc, srv)
}

func _ProductStockService_ListProductStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServiceServer).ListProductStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStockService_ListProductStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServiceServer).ListProductStocks(ctx, req.(*ListProductStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStockService_GetProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServiceServer).GetProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStockService_GetProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServiceServer).GetProductStock(ctx, req.(*GetProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStockService_CreateProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServiceServer).CreateProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStockService_CreateProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServiceServer).CreateProductStock(ctx, req.(*CreateProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStockService_DeleteProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServiceServer).DeleteProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStockService_DeleteProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServiceServer).DeleteProductStock(ctx, req.(*DeleteProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductStockService_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductStockServiceServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductStockService_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductStockServiceServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductStockService_ServiceDesc is the grpc.ServiceDesc for ProductStockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductStockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_stock.v1.ProductStockService",
	HandlerType: (*ProductStockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductStocks",
			Handler:    _ProductStockService_ListProductStocks_Handler,
		},
		{
			MethodName: "GetProductStock",
			Handler:    _ProductStockService_GetProductStock_Handler,
		},
		{
			MethodName: "CreateProductStock",
			Handler:    _ProductStockService_CreateProductStock_Handler,
		},
		{
			MethodName: "DeleteProductStock",
			Handler:    _ProductStockService_DeleteProductStock_Handler,
		},
		{
			MethodName: "ReserveStock",
			Handler:    _ProductStockService_ReserveStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_stock/v1/product_stock.proto",
}
